spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
spring.cloud.stream.bindings.outputEvents.contentType: application/json
spring.cloud.stream.kafka.streams.binder.brokers: ${KAFKA_SERVERS:localhost:9092}
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
#spring.cloud.stream.kafka.streams.binder.configuration:
#  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.outputEvents:
  destination: events-checked
  producer:
    headerMode: raw
spring.cloud.stream.bindings.inputEvents:
  destination: events
  consumer:
    headerMode: raw
customer:
  service-url: ${CUSTOMER_SERVICE:http://localhost:8080/customers}
logging:
  level:
    root: INFO
    es.eci.elejandria: DEBUG